### ISSUE TITLE
Support on_push cmds for branches other than master

### ISSUE THREAD

**Issue by jbuck** [arturadib/botio#5]
Our use case here is that in butter we currently have two branches, one for development work and the other that will be for bugfixes only as we get ready for the Mozilla Summer of Code party. We have our own dev environment that I'd like to keep up to date using botio, rather than a crontab every 5 minutes, that pulls from the stable branch. Right now, botio only supports on_push commands for master, and I think it would make sense to expand that. What would be the best way to implement this, from a script perspective?

1) Keep current scripts working and add new branch support by adding to the file name
- `on_push.js` handles `master` 
- `on_stable_push.js` handles `stable` or `on_push_stable.js` handles `stable`

2) Break existing scripts and manually specify branch names
- `on_push.js` handles all branches (is this a valid use case? maybe...)
- `on_master_push.js` handles `master` or `on_push_master.js` handles `master`
- `on_stable_push.js` handles `stable` or `on_push_stable.js` handles `stable`

**Comment by arturadib** [comment]
Closed in #7
